server:
  port: 8081

spring:
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\learn\bobocode\nasa-microservices\config-service\src\main\resources\config